tech_keyword_list = [
    "Python",
    "C",
    "C++",
    "Java",
    "C#",
    "Visual Basic",
    "NET",
    "JavaScript ",
    "SQL",
    "Assembly",
    "PHP",
    "R",
    "Go"
    "Classic Visual Basic",
    "MATLAB",
    "Swift",
    "Delphi",
    "Object Pascal",
    "Ruby",
    "Perl",
    "Objective-C",
    "Rust",
    "Scratch",
    "SAS",
    "Kotlin",
    "Julia",
    "Lua",
    "Fortran",
    "COBOL",
    "Lisp",
    "FoxPro",
    "Ada",
    "Dart",
    "Scala",
    "Prolog",
    "Dlang",
    "Bash",
    "Powershell",
    "Haskell",
    "Power BI",
    "Azure",
    "AWS",
    "OAuth",
    "D365",
    "CSS",
    "SSRS",
    "Web API",
    "Rest API",
    "SCRUM",
    "Power Automate",
    "owasp",
    "jenkins",
    "Spring Boot",
    "React",
    "Django",
    "Angular",
    "Svelte",
    "JQuery",
    "NexJS",
    "VMWare",
    "Apache",
    "nginx",
    "JIRA",
    "Linux",
    "Unix",
    "Drupal",
    "etl",
    "data lake",
    "data warehouse",
    "confluence",
    "Visio",
    "plantir",
    "mulesoft",
    "salesforce",
    "sap",
    "oracle",
    "juniper",
    "cisco",
    "clearswift",
    "tableau",
    "uipath",
    "rpa",
    "splunk",
    "ux",
    "ui",
    "figma",
    "hcl",
    "cloud",
    "bicep",
    "terraform",
    "azure ad",
    "iaas",
    "power platform",
    "automation",
    "devops",
    "project manager",
    "dax",
    "scripting",
    "api development",
    "node",
    "redshift",
    "synapse",
    "big query",
    "blazor",
    "edrms",
    "system administrator",
    "sysadmin",
    "TM1",
    "aurion",
    "actuary",
    "actuarial",
    "aws connect",
    "service desk",
    "gitlab",
    'voip',
    "itil",
    "sdlc",
    "itsm",
    "red hat",
    "redhat",
    "forman",
    'satellite',
    'ansible',
    'puppet',
    "togaf",
    "pspf",
    "restful",
    "jwt",
    "soap",
    "graphql",
    "microservices",
    "kubernetes",
    "docker",
    "ci cd",
    "dynamics 365",
    "crm",
    "agile",
    "ai",
    "ml",
    "iac",
    "nutanix",
    "geospatial",
    "sharepoint"
]